
format = """$os\
[$username](bold prev_fg)( $cmd_duration) in\
[$directory](bold fg:lv2)\
[$git_branch](bold fg:lv3)\
$git_commit\
$git_status\
(\
    [ via](lv0)\
    $c\
    $cpp\
    $rust\
    $golang\
    $nodejs\
    $php\
    $java\
    $kotlin\
    $haskell\
    $python\
)\
(\
    [ under](lv0)\
    $docker_context\
    $conda\
    $pixi\
)\
[$time](lv0)\
$line_break$character
"""

palette = 'nobg'
add_newline = false

[palettes.nobg]
lv0 = '#ebebeb'
lv1 = '#50d9ff'
lv2 = '#de8100'
lv3 = '#F34F29'
lvd = '#929292'
gitahead = '#00aaff'
gitconflict = '#ff0000'
gitdiverged = '#c8c800'
gitbehind = '#a3e2a3'
gituptodate = '#5bdd5b'
gituntracked = '#fbff00'
gitstashed = '#de8100'
gitmodified = '#91f8ff'
gitstaged = '#61ffba'
gitdeleted = '#a5a5a5'

[os]
format = " $symbol"
disabled = false
# style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "[󰍲](fg:#0173D0)"
Ubuntu = "[](fg:#E95420)"
SUSE = "[](fg:#30B878)"
Raspbian = "[](fg:#CD1D55)"
Mint = "[󰣭](fg:#86BE43)"
Macos = "[󰀵](fg:#8D8D8D)"
Manjaro = "[](fg:#34be5b)"
Linux = "[](fg:#F7C631)"
Gentoo = "[](fg:#6E56AF)"
Fedora = "[](fg:#51A2DA)"
Alpine = "[](fg:#0D597F)"
Amazon = "[󰸏](fg:#FF9900)"
Android = "[](fg:#3ddc84)"
AOSC = "[](fg:#C00000)"
Arch = "[](fg:#1793D1)"
Artix = "[](fg:#0797CF)"
EndeavourOS = "[](fg:#7F3FBF)"
CentOS = "[](fg:#A14F8C)"
Debian = "[](fg:#CE0056)"
Redhat = "[󱄛](fg:#E70000)"
RedHatEnterprise = "[󱄛](fg:#E70000)"
Pop = "[](fg:#46B3C1)"

[username]
show_always = true
# style_user = "bg:color_orange fg:color_fg0"
# style_root = "bg:color_orange fg:color_fg0"
format = ' $user'

[directory]
# style = "fg:color_fg0 bg:color_yellow"
format = " $path"
truncation_length = 5
truncation_symbol = "/"
truncate_to_repo = false
home_symbol = ' '
repo_root_style = "bold lv3"
before_repo_root_style = ""
repo_root_format = """ [󰊢 ](lv3)\
    [$repo_root]($repo_root_style)\
    [$path]($bold cyan)\
    [$read_only]($read_only_style)[ on](lv0)\
"""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "
# "~" = " "
# "git" = "󰊢 "

[git_branch]
symbol = ""
# style = "bg:color_aqua"
format = ' $symbol $branch'

[git_commit]
style ="green"
format = ' [\($hash$tag\)]($style)'
tag_disabled = false
# only_detached = false
tag_symbol = "  "
tag_max_candidates = 3

[git_status]
# style = "bg:color_aqua"
format = '$all_status$ahead_behind'
conflicted = '[  ](bold gitconflict)'
ahead = '[  +($count)](bold gitahead)'
behind = '[ 󱙷 +($count)](bold gitbehind)'
diverged = '[ \[󰃻 : [ ${ahead_count}](bold gitahead) [ ${behind_count}](bold gitbehind)\]](gitdiverged)' #'[ 󰃻 :󱞽 ${ahead_count} 󱞣 ${behind_count}](gitdiverged)'
up_to_date = '[  ](gituptodate)'
untracked = '[  +($count)](bold gituntracked)'
stashed = '[ 󱧘 +($count)](bold gitstashed)'
modified = '[  +($count)](bold gitmodified)'
staged = '[  +($count)](bold gitstaged)'
renamed = '[  +($count)](bold gitmodified)'
deleted = '[  +($count)](bold gitdeleted)'

[nodejs]
symbol = " "
style = "bold #68A063"
format = " [$symbol($version)]($style)"
#'[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bold #7da7d6"
format = ' [$symbol($name( $version))]($style)'
commands = [ [ "clang", "--version" ], [ "cc", "--version" ], [ "gcc", "--version" ] ]
detect_extensions = ["c", "!cpp", "!cxx", "!cc", "!hpp"]

[cpp]
disabled = false
symbol = " "
style = "bold #7da7d6"
format = ' [$symbol($name( $version))]($style)'
commands = [ [ "clang++", "--version" ], [ "cc", "--version" ], [ "g++", "--version" ]]

[rust]
symbol = " "
style = "bold #b19371"
format = " [$symbol($version)]($style)"
# format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = "󰟓 "
style = "bold #00ADD8"
format = " [$symbol($version)]($style)"
#'[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = " "
style = "bold #8892BE"
format = " [$symbol($version)]($style)"
#'[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bold #f89820"
format = " [$symbol($version)]($style)"

[kotlin]
symbol = " "
style = "bold #ff5ae1"
format = " [$symbol($version)]($style)"

[haskell]
symbol = " "
style = "bold #a087e2"
format = " [$symbol($version)]($style)" #'[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = " "
style = "bold #4B8BBE"
format = ' [$symbol($version)]($style)'

[docker_context]
symbol = " "
style = "bold #1D63ED"
format = ' [$symbol($context)]($style)'

[conda]
symbol = " "
ignore_base = false
# symbol = " "
style = "bold #43B049"
format = ' [$symbol($environment)]($style)'

[pixi]
symbol = " "
style = "bold #FFD43B"
format = ' [$symbol($version)( $environment)]($style)'

[time]
disabled = false
time_format = "%R"
format = '  $time'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[\$](bold fg:green)'
error_symbol = '[\$](bold fg:red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[cmd_duration]
min_time = 2_000
show_milliseconds = true
format = "[󰜎 $duration](bold yellow)"
